targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          - lib/**
        options:
          class_name_pattern: "^_?[A-Z][a-zA-Z0-9]*$"
          
      json_serializable:json_serializable:
        enabled: true
        generate_for:
          - lib/**
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
          
      retrofit_generator:retrofit_generator:
        enabled: true
        generate_for:
          - lib/**
        options:
          null_safe: true
          
      freezed:freezed:
        enabled: true
        generate_for:
          - lib/**
